### PR TITLE
feat(install): add airgap installation support

### PR DESCRIPTION
**Pull request by sagarkrsd**
This PR does the following:

- Configured the component's container images to make use of the custom registry for images outside of openebs/ repository also such as image being pulled from `quay.io/k8scsi...` registry, etc.

- Refactored one of the functions related to `openebs-csi-controller` to be more modular.

Above will help in the OpenEBS installation to be successful even in cases of airgap setup where there is not internet connectivity and all and all the images need to be pulled from a local registry.

Signed-off-by: sagarkrsd <sagar.kumar@mayadata.io>

### CODE REVIEW

**Comment by AmitKumarDas** [comment]
Will it be possible to put some E to E testing on these changes

**Comment by sagarkrsd** [comment]
Sure @amitd, should that be included in this PR only or a separate PR will also do the job.

**Comment by AmitKumarDas** [comment]
Let's list a set of positive and negative test cases due to this PR and PRs that were checked in last 3 releases. Create an issue with the list of these Todo tests. Please plan ahead to finish these test implementations in upcoming PRs. The new enhancements or fixes should come along with tests.

**Comment by sagarkrsd** [comment]
Sure @amitd, will do that.
Thanks.

**Comment by sagarkrsd** [comment]
@AmitKumarDas Issue link for test case implementation: https://github.com/mayadata-io/openebs-upgrade/issues/41

**Pull request merged**
